//
// Created by xflajs00 on 15.03.2023.
//

#pragma once


#define SPECULO_COMBINE_MACRO2_INNER(x, y) x##y
#define SPECULO_COMBINE_MACRO2(x, y) SPECULO_COMBINE_MACRO2_INNER(x, y)
#define SPECULO_COMBINE_MACRO4_INNER(x, y, z, w) x##y##z##w
#define SPECULO_COMBINE_MACRO4(x, y, z, w) SPECULO_COMBINE_MACRO4_INNER(x, y, z, w)


#ifdef SPECULO_CODE_GENERATOR_RUNNING
#define SPECULO_GENERATED()
#define SPECULO_GENERATED_HEADER()
#else
#define SPECULO_GENERATED() SPECULO_COMBINE_MACRO4(SPECULO_GENERATED_, __LINE__, _, SPECULO_GENERATED_FILE_ID)
#define SPECULO_GENERATED_HEADER() SPECULO_COMBINE_MACRO2(SPECULO_GENERATED_HEADER_, SPECULO_GENERATED_FILE_ID)
#endif


#define SPECULO_REFLECT(X) ::speculo::details::provideReflectInfo<X>().Result

#define SPECULO_SPLICE(I) ::speculo::details::SpliceResultProvider<I>::Result
